server:
  port: 9998
eureka:
  instance:
    hostname: 127.0.0.1
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9999/eureka/
spring:
  application:
    name: eureka-user-manager     #注册的系统名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uc?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml



